### ISSUE TITLE
Different color for macros

### ISSUE THREAD

**Issue by Turbo87** [alexeykudinkin/intellij-rust#88]
I think it would be a good idea to highlight macros different than normal function calls. At the moment they all seem to be "Identifiers"

**Comment by chriskrycho** [comment]
:+1: on this. Although macros are safe and hygienic, they do behave very differently from function calls in many ways, and for things like `try!` in particular, that's important to highlight, lest something go :boom: and surprise you.

**Comment by pavel-v-chernykh** [comment]
Partially implemented. Need some resolution on ```macro_rules!```  #98

**Comment by matklad** [comment]
@pavel-v-chernykh considering #98, `item_macro` is used mainly for macro definition (` macro_rules! foo {...}`). 

I think the way we treat macro definitions will change hugely in some point in future, so it does not make sense to build anything on top of the current implementation of `item_macro`. 

Besides, macro expression usage is a much more common use case then macro definition, and macro usage **is** highlighted properly (thanks! :) ) .

So I'm going to close this, because it is implemented, and also close #98, because there are more severe problems with `item_macro`, then a missing identifier.

**Comment by pavel-v-chernykh** [comment]
:+1:
